# Generated by Django 5.1.6 on 2025-02-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_weaviate_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='weaviate_ids',
            field=models.JSONField(default=dict),
        ),
    ]
