# Generated by Django 5.1.6 on 2025-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_file_weaviate_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sample_questions',
            field=models.JSONField(default=list),
        ),
    ]
