# Generated by Django 5.1.6 on 2025-02-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_file_sample_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='sample_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
